FROM node:22-alpine AS builder


# Create app directory
WORKDIR /build

COPY . .

# Install dependencies
RUN npm install

# Build the project
RUN npm run build

# Stage 2: producción
FROM node:22-alpine AS production

# Create non-root user for security
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001

RUN apk add --no-cache \
    ffmpeg \
    dumb-init \
    && rm -rf /var/cache/apk/*

# Definir argumentos de build
ARG LLM_API_KEY
ARG STEAM_API_KEY
ARG SESSION_SECRET
ARG STEAM_RETURN_URL
ARG DOMAIN
ARG MONGODB_URI

WORKDIR /app
COPY --from=builder /build/package*.json ./
COPY --from=builder /build/backend ./backend
COPY --from=builder /build/static ./static


# Install only production dependencies
RUN npm ci --only=production && npm cache clean --force

# Change ownership to nodejs user
RUN chown -R nodejs:nodejs /app
USER nodejs



# Configurar las variables de entorno desde los argumentos de build
ENV LLM_API_KEY=${LLM_API_KEY}
ENV STEAM_API_KEY=${STEAM_API_KEY}
ENV SESSION_SECRET=${SESSION_SECRET}
ENV STEAM_RETURN_URL=${STEAM_RETURN_URL}
ENV DOMAIN=${DOMAIN}
ENV MONGODB_URI=${MONGODB_URI}
ENV NODE_ENV="production"

EXPOSE 3000

# Use dumb-init for proper signal handling
ENTRYPOINT ["dumb-init", "--"]

CMD ["node", "backend/src/index.js"]