FROM node:22-alpine AS builder


# Create app directory
WORKDIR /build

COPY . .

# Install dependencies
RUN npm install

# Build the project
RUN npm run build

# Stage 2: producción
FROM node:22-alpine AS production
# Instala solo FFmpeg runtime
RUN apk add --no-cache ffmpeg

# Definir argumentos de build
ARG LLM_API_KEY
ARG STEAM_API_KEY
ARG SESSION_SECRET
ARG STEAM_RETURN_URL
ARG DOMAIN
ARG MONGODB_URI

WORKDIR /app
COPY --from=builder /build/backend ./backend
COPY --from=builder /build/package.json ./package.json
COPY --from=builder /build/static ./static

RUN npm install --production

EXPOSE 3000

# Configurar las variables de entorno desde los argumentos de build
ENV LLM_API_KEY=${LLM_API_KEY}
ENV STEAM_API_KEY=${STEAM_API_KEY}
ENV SESSION_SECRET=${SESSION_SECRET}
ENV STEAM_RETURN_URL=${STEAM_RETURN_URL}
ENV DOMAIN=${DOMAIN}
ENV MONGODB_URI=${MONGODB_URI}
ENV NODE_ENV="production"

CMD ["node", "backend/src/index.js"]